ALTER TABLE week_issue_record
ADD COLUMN better TEXT,
ADD COLUMN front TINYTEXT,
ADD COLUMN good1 TINYTEXT,
ADD COLUMN good2 TINYTEXT,
ADD COLUMN good3 TINYTEXT,
ADD COLUMN reading TINYTEXT,
ADD COLUMN sport VARCHAR,
ADD COLUMN ted VARCHAR(255),
ADD COLUMN video VARCHAR(255);