CREATE TABLE IF NOT EXISTS year_plan_item (
	id INT NOT NULL AUTO_INCREMENT,
	user_id INT NOT NULL,
	plan_year INT NOT NULL,
	group_key VARCHAR(32) NOT NULL,
	sort_order INT NOT NULL DEFAULT 0,
	code VARCHAR(64) NULL,
	title VARCHAR(200) NOT NULL,
	kind VARCHAR(32) NOT NULL,
	scene VARCHAR(32) NULL,
	ref_id INT NULL,
	expect_status VARCHAR(32) NULL,
	metric VARCHAR(32) NULL,
	target_value DECIMAL(12, 2) NULL,
	result_text TEXT NULL,
	stages_json TEXT NULL,
	struck TINYINT(1) NOT NULL DEFAULT 0,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL,
	PRIMARY KEY (id),
	KEY idx_year_plan_user_year (user_id, plan_year)
);
