CREATE TABLE IF NOT EXISTS `ltn_daily_coins` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `date` VARCHAR(10) NOT NULL COMMENT 'YYYY-MM-DD',
  `coins` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_date` (`date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;